<?php
/**
 * =====================================================
 * SaQshi Security Layer
 * security.php
 * Production
 * =====================================================
 */

/* =====================================================
   PREVENT MULTIPLE LOAD
===================================================== */

if (defined('SAQSHI_SECURITY_LOADED')) {
    return;
}

define('SAQSHI_SECURITY_LOADED', true);

/*
 * CSP nonces allow the existing inline scripts and styles to execute without
 * permitting arbitrary inline content injected by an attacker.  The output
 * callback adds the nonce to inline <script> and <style> tags generated by
 * legacy templates; external assets remain governed by their allow-lists.
 */
if (empty($_SESSION['csp_nonce'])) {
    $_SESSION['csp_nonce'] = rtrim(strtr(base64_encode(random_bytes(18)), '+/', '-_'), '=');
}
$cspNonce = $_SESSION['csp_nonce'];

if (!defined('SAQSHI_CSP_NONCE_BUFFER')) {
    define('SAQSHI_CSP_NONCE_BUFFER', true);
    ob_start(static function (string $html) use ($cspNonce): string {
        $nonceAttribute = ' nonce="' . htmlspecialchars($cspNonce, ENT_QUOTES, 'UTF-8') . '"';
        $csrfField = '<input type="hidden" name="csrf_token" value="' .
            htmlspecialchars((string)($_SESSION['csrf_token'] ?? ''), ENT_QUOTES, 'UTF-8') . '">';
        // Source comments have been reported by VAPT as information leakage.
        // Keep IE conditional comments intact, but remove ordinary comments
        // from responses generated through the shared application shell.
        $html = preg_replace('/<!--(?!\[if)[\s\S]*?-->/i', '', $html);
        $html = preg_replace_callback(
            '/<script\\b([^>]*)>/i',
            static function (array $match) use ($nonceAttribute): string {
                if (preg_match('/\\bsrc\\s*=|\\bnonce\\s*=/i', $match[1])) {
                    return $match[0];
                }
                return '<script' . $match[1] . $nonceAttribute . '>';
            },
            $html
        );
        $html = preg_replace_callback(
            '/<style\\b([^>]*)>/i',
            static function (array $match) use ($nonceAttribute): string {
                if (preg_match('/\\bnonce\\s*=/i', $match[1])) {
                    return $match[0];
                }
                return '<style' . $match[1] . $nonceAttribute . '>';
            },
            $html
        );
        return preg_replace(
            '/<form\\b(?=[^>]*\\bmethod\\s*=\\s*["\\\']?post\\b)([^>]*)>/i',
            '<form$1>' . $csrfField,
            $html
        );
    });
}

/* =====================================================
   SECURITY HEADERS
===================================================== */

header("X-Frame-Options: DENY");

header("X-Content-Type-Options: nosniff");

header("Referrer-Policy: strict-origin");

header("Permissions-Policy: geolocation=()");

header("Cross-Origin-Opener-Policy: same-origin");

header("Cross-Origin-Resource-Policy: same-origin");

header("X-Permitted-Cross-Domain-Policies: none");

// Do not allow a page-specific include to accidentally make authenticated
// responses readable by arbitrary origins.  Public APIs that genuinely need
// CORS must opt in with an explicit allow-list at the endpoint/proxy layer.
header_remove("Access-Control-Allow-Origin");

header(
    "Strict-Transport-Security: max-age=31536000; includeSubDomains"
);

$csp =
    "default-src 'self'; " .
    "script-src 'self' 'nonce-{$cspNonce}' https://cdnjs.cloudflare.com https://cdn.jsdelivr.net https://code.jquery.com https://unpkg.com; " .
    "style-src 'self' 'nonce-{$cspNonce}' https://cdn.jsdelivr.net https://fonts.googleapis.com https://unpkg.com; " .
    "font-src 'self' https://fonts.gstatic.com https://cdn.jsdelivr.net data:; " .
    "img-src 'self' data: blob: https://maps.gstatic.com https://*.tile.openstreetmap.org https://tile.openstreetmap.org https://unpkg.com; " .
    "connect-src 'self' https://maps.gstatic.com https://*.tile.openstreetmap.org https://tile.openstreetmap.org; " .
    "frame-ancestors 'none'; " .
    "form-action 'self'; " .
    "object-src 'none'; " .
    "base-uri 'self';";

header("Content-Security-Policy: " . $csp);
header(
    "Cache-Control: no-store, no-cache, must-revalidate, max-age=0"
);

header("Pragma: no-cache");

header("Expires: Sat, 01 Jan 2000 00:00:00 GMT");

/* =====================================================
   PHP ERROR SETTINGS
===================================================== */

ini_set('display_errors', 0);

ini_set('log_errors', 1);

error_reporting(E_ALL);

/* =====================================================
   CSRF TOKEN
===================================================== */

if (
    session_status() === PHP_SESSION_ACTIVE &&
    empty($_SESSION['csrf_token'])
) {

    if (empty($_SESSION['csrf_token'])) {

    $_SESSION['csrf_token'] =
        bin2hex(random_bytes(32));
}
}
/* =====================================================
   CSRF HELPER
===================================================== */

if (!function_exists('csrf')) {

    function csrf()
    {
        return '
        <input type="hidden"
               name="csrf_token"
               value="' .
               $_SESSION['csrf_token'] .
               '">';
    }
}
/* =====================================================
   CSRF VALIDATION
===================================================== */

if (
    session_status() === PHP_SESSION_ACTIVE &&
    $_SERVER['REQUEST_METHOD'] === 'POST'
) {

    if (
        empty($_POST['csrf_token']) ||
        !hash_equals(
            $_SESSION['csrf_token'],
            $_POST['csrf_token']
        )
    ) {

        http_response_code(403);

        exit("Invalid CSRF Token");
    }
}

/* =====================================================
   SAFE OUTPUT FUNCTION
===================================================== */

function e($string)
{
    return htmlspecialchars(
        (string)($string ?? ''),
        ENT_QUOTES,
        'UTF-8'
    );
}

/* =====================================================
   SAFE INPUT FUNCTION
===================================================== */

if (!function_exists('cleanInput')) {

    function cleanInput($data)
    {
        return trim(
            htmlspecialchars(
                (string)$data,
                ENT_QUOTES,
                'UTF-8'
            )
        );
    }
}

/* =====================================================
   SAFE INTEGER
===================================================== */

if (!function_exists('cleanInt')) {

    function cleanInt($value)
    {
        return (int)$value;
    }
}

/* =====================================================
   SAFE REDIRECT
===================================================== */

if (!function_exists('safeRedirect')) {

    function safeRedirect($url)
    {
        header("Location: " . $url);

        exit;
    }
}

/* =====================================================
   ROLE AUTHORIZATION
===================================================== */

if (!function_exists('requireRole')) {

    function requireRole($roles = [])
    {

        if (
            empty($_SESSION['userrole']) ||
            !in_array(
                $_SESSION['userrole'],
                $roles
            )
        ) {

            http_response_code(403);

            exit("Unauthorized Access");
        }
    }
}

/* =====================================================
   AJAX VALIDATION
===================================================== */

if (!function_exists('requireAjax')) {

    function requireAjax()
    {

        if (
            strtolower(
                $_SERVER['HTTP_X_REQUESTED_WITH']
                ?? ''
            ) !== 'xmlhttprequest'
        ) {

            http_response_code(403);

            exit("Invalid Request");
        }
    }
}

/* =====================================================
   SIMPLE RATE LIMIT
===================================================== */

if (session_status() === PHP_SESSION_ACTIVE) {

    if (!isset($_SESSION['rate_limit'])) {

        $_SESSION['rate_limit'] = [];
    }

    $currentMinute =
        floor(time() / 60);

    if (
        !isset(
            $_SESSION['rate_limit'][$currentMinute]
        )
    ) {

        $_SESSION['rate_limit']
            = [$currentMinute => 1];

    } else {

        $_SESSION['rate_limit'][$currentMinute]++;
    }

    if (
        $_SESSION['rate_limit'][$currentMinute]
        > 300
    ) {

        http_response_code(429);

        exit("Too many requests");
    }
}

/* =====================================================
   CLICKJACKING FRAME BREAK
===================================================== */

/* =====================================================
   SECURITY READY
===================================================== */
?>
